# Generated by Django 4.0.3 on 2023-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_description_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
