# Generated by Django 4.0.3 on 2023-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workoutmuscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workoutmuscles')),
                ('musclevarities', models.TextField(max_length=250)),
            ],
        ),
    ]
