# Generated by Django 4.0.3 on 2023-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_workoutmuscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadworkoutvideo',
            name='musclecategory',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
