# Generated by Django 4.0.3 on 2023-05-05 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_save'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='Favourites',
        ),
    ]
