# Generated by Django 4.0.3 on 2023-05-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_save_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favourite',
        ),
        migrations.AddField(
            model_name='favourites',
            name='favourite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.uploadworkoutvideo'),
            preserve_default=False,
        ),
    ]
