# Generated by Django 4.0.3 on 2023-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_favourites_favourite_favourites_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favourite',
        ),
        migrations.AddField(
            model_name='favourites',
            name='favourite',
            field=models.ManyToManyField(to='app.uploadworkoutvideo'),
        ),
    ]
