# Generated by Django 4.0.3 on 2023-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_favourites_favourite_favourites_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='vidfav',
            field=models.ManyToManyField(blank=True, related_name='vaooo', to='app.uploadworkoutvideo'),
        ),
    ]
