# Generated by Django 4.0.3 on 2023-05-14 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_remove_favourites_vidfav_remove_favourites_favourite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadworkoutvideo',
            name='workfollow',
            field=models.ManyToManyField(blank=True, related_name='vaooo', to=settings.AUTH_USER_MODEL),
        ),
    ]
