# Generated by Django 4.0.3 on 2023-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_uploadworkoutvideo_workfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadworkoutvideo',
            name='workfollow',
        ),
        migrations.AddField(
            model_name='uploadworkoutvideo',
            name='level',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
