# Generated by Django 4.0.3 on 2023-05-27 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadworkoutvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='workoutpost', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
